name: PR Workflow

on:
  pull_request:
    branches:
        - main
  workflow_dispatch:

jobs:
  job-poller:
    uses: ./.github/workflows/job-poller.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  linter:
    uses: ./github/workflows/linter.yml
    permissions:
        id-token: write
        contents: read
  
  pr-preview:
    uses: ./.github/workflows/pr-preview.yml
    needs: 
        - job-poller
        - linter
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    secrets: inherit
